apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels: 
        app: nginx
    spec:
      containers:
        - name: nginx
          image: satish680/my-nginx:accion
          ports:
            - containerPort: 80
          volumeMounts: 
            - name: nginx-storage
              mountPath: /usr/share/nginx/html
          resources: 
            limits: 
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "256m"
              memory: "128Mi"         
    volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: efs-claim  # Refers to the PVC that uses EFS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi                     

