apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      lables: 
        app: nginx
    spec:
      conatiners:
        - name: nginx
          image: nginx:1.19-alpine
          ports:
            - conatinerPort: 80
          volumeMounts: 
            - name: nginx
              mountPath: /usr/share/nginx/html
          resources: 
            limits: 
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "256m"
              memory: "128Mi"
  volumeClaimTemplate:
    - metadata:
        name: nginx-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi                             

