name: CICD Pipeline

on: 
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: docker build -t nginx:accion .
            
            - name: Push image to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker tag nginx:accion satish680/my-nginx:accion
                docker push satish680/my-nginx:accion

            - name: Run Security Scan
              uses: aquasecurity/trivy-action@master
              with: 
                image-ref: satish680/my-nginx:accion
                
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
               aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
               aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
               aws-region: us-east-1   

            - name: Update kubeconfig  
              run: aws eks update-kubeconfig --name my-fargate-cluster --region us-east-1
               
            - name: Deploy on EKS Cluster
              run: kubectl apply -f nginx.yaml