name: CICD Pipeline

on: 
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker Image
              run: docker build -t nginix:accion .

            - name: Run Security Scan
              uses: aquasecurity/trivy-action@master
              with: 
                image-ref: nginx:accion
            
            - name: Push image to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker tag my-nginx:accion satish680/my-nginx:accion
                docker push satish680/my-nginx:accion   
              
